# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'atlas_surface_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_atlas_surface_page(object):
    def setupUi(self, atlas_surface_page):
        atlas_surface_page.setObjectName("atlas_surface_page")
        atlas_surface_page.resize(847, 551)
        self.verticalLayout = QtWidgets.QVBoxLayout(atlas_surface_page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.StrongBodyLabel = StrongBodyLabel(atlas_surface_page)
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.horizontalLayout.addWidget(self.StrongBodyLabel)
        self.choose_colorbar_cbb = ComboBox(atlas_surface_page)
        self.choose_colorbar_cbb.setObjectName("choose_colorbar_cbb")
        self.horizontalLayout.addWidget(self.choose_colorbar_cbb)
        self.StrongBodyLabel_2 = StrongBodyLabel(atlas_surface_page)
        self.StrongBodyLabel_2.setObjectName("StrongBodyLabel_2")
        self.horizontalLayout.addWidget(self.StrongBodyLabel_2)
        self.color_number_edit = LineEdit(atlas_surface_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.color_number_edit.sizePolicy().hasHeightForWidth())
        self.color_number_edit.setSizePolicy(sizePolicy)
        self.color_number_edit.setObjectName("color_number_edit")
        self.horizontalLayout.addWidget(self.color_number_edit)
        self.StrongBodyLabel_3 = StrongBodyLabel(atlas_surface_page)
        self.StrongBodyLabel_3.setObjectName("StrongBodyLabel_3")
        self.horizontalLayout.addWidget(self.StrongBodyLabel_3)
        self.choose_shader_cbb = ComboBox(atlas_surface_page)
        self.choose_shader_cbb.setObjectName("choose_shader_cbb")
        self.horizontalLayout.addWidget(self.choose_shader_cbb)
        self.StrongBodyLabel_4 = StrongBodyLabel(atlas_surface_page)
        self.StrongBodyLabel_4.setObjectName("StrongBodyLabel_4")
        self.horizontalLayout.addWidget(self.StrongBodyLabel_4)
        self.base_color_slider = Slider(atlas_surface_page)
        self.base_color_slider.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.base_color_slider.sizePolicy().hasHeightForWidth())
        self.base_color_slider.setSizePolicy(sizePolicy)
        self.base_color_slider.setMinimumSize(QtCore.QSize(200, 24))
        self.base_color_slider.setMaximum(100)
        self.base_color_slider.setOrientation(QtCore.Qt.Horizontal)
        self.base_color_slider.setObjectName("base_color_slider")
        self.horizontalLayout.addWidget(self.base_color_slider)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.brain_regions_panel = BrainRegionsPanel(atlas_surface_page)
        self.brain_regions_panel.setObjectName("brain_regions_panel")
        self.horizontalLayout_3.addWidget(self.brain_regions_panel)
        self.atlas_surface_view_widget = AtlasSurfaceViewWidget()
        self.atlas_surface_view_widget.setObjectName("atlas_surface_view_widget")
        self.horizontalLayout_3.addWidget(self.atlas_surface_view_widget)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(atlas_surface_page)
        QtCore.QMetaObject.connectSlotsByName(atlas_surface_page)

    def retranslateUi(self, atlas_surface_page):
        _translate = QtCore.QCoreApplication.translate
        atlas_surface_page.setWindowTitle(_translate("atlas_surface_page", "Form"))
        self.StrongBodyLabel.setText(_translate("atlas_surface_page", "ColorBar:"))
        self.choose_colorbar_cbb.setText(_translate("atlas_surface_page", "Choose..."))
        self.StrongBodyLabel_2.setText(_translate("atlas_surface_page", "Color Numbers"))
        self.color_number_edit.setText(_translate("atlas_surface_page", "20"))
        self.StrongBodyLabel_3.setText(_translate("atlas_surface_page", "Shader"))
        self.choose_shader_cbb.setText(_translate("atlas_surface_page", "Choose"))
        self.StrongBodyLabel_4.setText(_translate("atlas_surface_page", "Base Color"))
from qfluentwidgets import ComboBox, LineEdit, Slider, StrongBodyLabel
from zjb.gui.panels.brain_regions_panel import BrainRegionsPanel
from zjb.main.visualization.surface_space import AtlasSurfaceViewWidget
