# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connectivity_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_connectivity_page(object):
    def setupUi(self, connectivity_page):
        connectivity_page.setObjectName("connectivity_page")
        connectivity_page.resize(1027, 646)
        self.horizontalLayout = QtWidgets.QHBoxLayout(connectivity_page)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(connectivity_page)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.brain_regions_panel = BrainRegionsPanel(self.splitter)
        self.brain_regions_panel.setObjectName("brain_regions_panel")
        self.connectivity_widget = ConnectivityWidget(self.splitter)
        self.connectivity_widget.setObjectName("connectivity_widget")
        self.circos_widget = MplWidget(self.splitter)
        self.circos_widget.setObjectName("circos_widget")
        self.horizontalLayout.addWidget(self.splitter)
        self.splitter.raise_()
        self.splitter.raise_()
        self.brain_regions_panel.raise_()

        self.retranslateUi(connectivity_page)
        QtCore.QMetaObject.connectSlotsByName(connectivity_page)

    def retranslateUi(self, connectivity_page):
        _translate = QtCore.QCoreApplication.translate
        connectivity_page.setWindowTitle(_translate("connectivity_page", "Form"))
from zjb.gui.panels.brain_regions_panel import BrainRegionsPanel
from zjb.gui.widgets.connectivity_widget import ConnectivityWidget
from zjb.gui.widgets.mpl_widget import MplWidget
