# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dynamics_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dynamics_page(object):
    def setupUi(self, dynamics_page):
        dynamics_page.setObjectName("dynamics_page")
        dynamics_page.resize(1235, 564)
        self.verticalLayout = QtWidgets.QVBoxLayout(dynamics_page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dm_info_button = TransparentTogglePushButton(dynamics_page)
        self.dm_info_button.setObjectName("dm_info_button")
        self.horizontalLayout.addWidget(self.dm_info_button)
        self.phase_plane_analysis_button = TransparentTogglePushButton(dynamics_page)
        self.phase_plane_analysis_button.setObjectName("phase_plane_analysis_button")
        self.horizontalLayout.addWidget(self.phase_plane_analysis_button)
        self.bifurcation_analysis_button = TransparentTogglePushButton(dynamics_page)
        self.bifurcation_analysis_button.setObjectName("bifurcation_analysis_button")
        self.horizontalLayout.addWidget(self.bifurcation_analysis_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.stackedWidget = QtWidgets.QStackedWidget(dynamics_page)
        self.stackedWidget.setObjectName("stackedWidget")
        self.dm_info_page = QtWidgets.QWidget()
        self.dm_info_page.setObjectName("dm_info_page")
        self.dm_info_page_verticalLayout = QtWidgets.QVBoxLayout(self.dm_info_page)
        self.dm_info_page_verticalLayout.setObjectName("dm_info_page_verticalLayout")
        self.stackedWidget.addWidget(self.dm_info_page)
        self.phase_plane_page = QtWidgets.QWidget()
        self.phase_plane_page.setObjectName("phase_plane_page")
        self.phase_plane_page_verticalLayout = QtWidgets.QVBoxLayout(self.phase_plane_page)
        self.phase_plane_page_verticalLayout.setObjectName("phase_plane_page_verticalLayout")
        self.stackedWidget.addWidget(self.phase_plane_page)
        self.bifurcation_page = QtWidgets.QWidget()
        self.bifurcation_page.setObjectName("bifurcation_page")
        self.bifurcation_page_verticalLayout = QtWidgets.QVBoxLayout(self.bifurcation_page)
        self.bifurcation_page_verticalLayout.setObjectName("bifurcation_page_verticalLayout")
        self.stackedWidget.addWidget(self.bifurcation_page)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(dynamics_page)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(dynamics_page)

    def retranslateUi(self, dynamics_page):
        _translate = QtCore.QCoreApplication.translate
        dynamics_page.setWindowTitle(_translate("dynamics_page", "Form"))
        self.dm_info_button.setText(_translate("dynamics_page", "Dynamic Model Infomation"))
        self.phase_plane_analysis_button.setText(_translate("dynamics_page", "Phase Plane Analysis"))
        self.bifurcation_analysis_button.setText(_translate("dynamics_page", "Bifurcation Analysis"))
from qfluentwidgets import TransparentTogglePushButton
